package com.deepak.movieinfo.utils

object DummyContent {

    var JSON_PAGE_1 = "{\"Search\":[{\"Title\":\"The Lord of the Rings: The Fellowship of the Ring\",\"Year\":\"2001\",\"imdbID\":\"tt0120737\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg\"},{\"Title\":\"The Lord of the Rings: The Return of the King\",\"Year\":\"2003\",\"imdbID\":\"tt0167260\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg\"},{\"Title\":\"The Lord of the Rings: The Two Towers\",\"Year\":\"2002\",\"imdbID\":\"tt0167261\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNGE5MzIyNTAtNWFlMC00NDA2LWJiMjItMjc4Yjg1OWM5NzhhXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg\"},{\"Title\":\"Lord of War\",\"Year\":\"2005\",\"imdbID\":\"tt0399295\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTYzZWE3MDAtZjZkMi00MzhlLTlhZDUtNmI2Zjg3OWVlZWI0XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg\"},{\"Title\":\"The Lord of the Rings\",\"Year\":\"1978\",\"imdbID\":\"tt0077869\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGMyNWJhZmYtNGQxYi00Y2ZjLWJmNjktNTgzZWJjOTg4YjM3L2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg\"},{\"Title\":\"Lord of the Flies\",\"Year\":\"1990\",\"imdbID\":\"tt0100054\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOTI2NTQyODk0M15BMl5BanBnXkFtZTcwNTQ3NDk0NA@@._V1_SX300.jpg\"},{\"Title\":\"Greystoke: The Legend of Tarzan, Lord of the Apes\",\"Year\":\"1984\",\"imdbID\":\"tt0087365\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTM5MzcwOTg4MF5BMl5BanBnXkFtZTgwOTQwMzQxMDE@._V1_SX300.jpg\"},{\"Title\":\"Lord of the Flies\",\"Year\":\"1963\",\"imdbID\":\"tt0057261\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BOGEwYTlhMTgtODBlNC00ZjgzLTk1ZmEtNmNkMTEwYTZiM2Y0XkEyXkFqcGdeQXVyMzU4Nzk4MDI@._V1_SX300.jpg\"},{\"Title\":\"Lord of Illusions\",\"Year\":\"1995\",\"imdbID\":\"tt0113690\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNDg1OTc0MDQwNl5BMl5BanBnXkFtZTcwMjQ3NDk0NA@@._V1_SX300.jpg\"},{\"Title\":\"Something the Lord Made\",\"Year\":\"2004\",\"imdbID\":\"tt0386792\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTIzNTE0NjU4N15BMl5BanBnXkFtZTcwNjgyNDcyMQ@@._V1_SX300.jpg\"}],\"totalResults\":\"501\",\"Response\":\"True\"}"

    var JSON_PAGE_2 = "{\"Search\":[{\"Title\":\"Red Riding: The Year of Our Lord 1974\",\"Year\":\"2009\",\"imdbID\":\"tt1259574\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTk3NTY0ODM4MV5BMl5BanBnXkFtZTcwNzMzMzExMw@@._V1_SX300.jpg\"},{\"Title\":\"Red Riding: The Year of Our Lord 1980\",\"Year\":\"2009\",\"imdbID\":\"tt1260581\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTk3NTY0ODM4MV5BMl5BanBnXkFtZTcwNzMzMzExMw@@._V1_SX300.jpg\"},{\"Title\":\"Phantasm III: Lord of the Dead\",\"Year\":\"1994\",\"imdbID\":\"tt0110823\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BNGE5Nzc5ZDUtYjQ4OC00OGU0LWE2YzEtMjE2NjRkYTFjYjgxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"},{\"Title\":\"Red Riding: The Year of Our Lord 1983\",\"Year\":\"2009\",\"imdbID\":\"tt1259573\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTk3NTY0ODM4MV5BMl5BanBnXkFtZTcwNzMzMzExMw@@._V1_SX300.jpg\"},{\"Title\":\"The Thief Lord\",\"Year\":\"2006\",\"imdbID\":\"tt0430674\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTY1MjAyMjAxMl5BMl5BanBnXkFtZTcwMjcwMDIzMQ@@._V1_SX300.jpg\"},{\"Title\":\"Dragon Ball Z: Lord Slug\",\"Year\":\"1991\",\"imdbID\":\"tt0142244\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BYjY0ODM5MzEtZmY3ZC00YWUwLTlkYjAtNjgyMjAwYTg1NTE5XkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg\"},{\"Title\":\"Little Lord Fauntleroy\",\"Year\":\"1980\",\"imdbID\":\"tt0081062\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BM2Q4NjI5ODEtZWVmMy00ZWVjLThhN2ItNzM1MGM3OTUxNzNjL2ltYWdlXkEyXkFqcGdeQXVyNzM0MDQ1Mw@@._V1_SX300.jpg\"},{\"Title\":\"Edges of the Lord\",\"Year\":\"2001\",\"imdbID\":\"tt0245090\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMTgyNDA2MDY2Ml5BMl5BanBnXkFtZTcwODE1MzMzMQ@@._V1_SX300.jpg\"},{\"Title\":\"Lord Jim\",\"Year\":\"1965\",\"imdbID\":\"tt0059399\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BZmEzNjliNjYtN2IzNC00ZmYwLTg0ZTUtZjEyOGEyYThkYzdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg\"},{\"Title\":\"At Play in the Fields of the Lord\",\"Year\":\"1991\",\"imdbID\":\"tt0101373\",\"Type\":\"movie\",\"Poster\":\"https://m.media-amazon.com/images/M/MV5BMDNlYTI3NjgtZWE4ZC00OTlkLWEyMmItZWIxNDQ2YjZjMmYzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg\"}],\"totalResults\":\"501\",\"Response\":\"True\"}"

    var ERROR_MANY_RESULTS = "{\"Response\":\"False\",\"Error\":\"Too many results.\"}"

    var ERROR_INVALID_API = "{\"Response\":\"False\",\"Error\":\"Invalid API key!\"}"

}
